version: '3'
services:
#####################################################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UPGRADE_PACKAGES: "true"
        VARIANT: "11"
    container_name: Lendit_Book_Kiosk-app
    volumes:
      # Forwards the local Docker socket to the container.
      # - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
    # Setup web app dependencies
    # depends_on:
    #   - db
    # links: 
    #   - db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    # expose:
    #   - 80
    #   - 8080
    network_mode: service:db
    # networks:
    #   lamp-network:
    #     ipv4_address: 172.16.238.20     # default gateway  172.16.238.1
    #     ipv6_address: 2001:3984:3989::10
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
#####################################################################
  db:
    image: mysql:8.0.27
    init: true
    container_name: Lendit_Book_Kiosk-db
    environment:
      # MySQL allow empty password variable
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # Name of the database
      MYSQL_DATABASE: 'Lendit_Book_Kiosk'
      # ##### MySQL Host variable:
      # # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'developer'
      # # You can use whatever password you like
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'developer'
      # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_passwd
      # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret_pub
      # MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret_key
    volumes:
      - mysql-data:/var/lib/mysql
      - ./logs/mysql-log:/var/log:rw
      - ./my_conf:/etc/mysql/conf.d
      - ../sql:/mysql_files
    #restart: "no"
    #restart: always
    restart: on-failure
    #restart: unless-stopped
    # expose:
    #   - 3306 
    #   - 33060
    # ports:
    #   - 3306:3306
      # - 55060:33060
    # networks:
    #   lamp-network:
    #     ipv4_address: 172.16.238.18    # default gateway  172.16.238.1
        #ipv6_address: 2001:3984:3989::9   
    # command:
    # - "mv /var/log/mysqld.log /var/log/mysqld.log.old"
    # - "&&"
    # - "install -omysql -gmysql -m0644 /dev/null /var/log/mysqld.log"    
    #command: ["--default-authentication-plugin=mysql_native_password"]
    #command: ["mysqld --verbose --help"]
    # secrets:
      # - mysql_passwd
      # - mysql_secret_key
      # - mysql_secret_pub
#####################################################################
  adminer:
    image: adminer:latest
    container_name: Lendit_Book_Kiosk-adminer
    restart: unless-stopped
    # expose:
    #   - 8181
    # depends_on:
    #   - db
    # links: 
    #   - db
    # command: 'php -S [::]:8181 -t /var/www/html'
    # - "php"
    # - "-S" 
    # - "[::]:8181"
    # - "-t" 
    # - "/var/www/html"
    entrypoint: 
    - "entrypoint.sh"
    - "docker-php-entrypoint"
    network_mode: service:db
################################# volumes ###########################
# since we are using direct access to host directories, we do not need to 
# declare any virtual volume mounts
#####################################################################
# NETWORKS
# networks:
#   lamp-network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.238.16/28
          #gateway: 172.16.238.1
        # - subnet: 2001:3984:3989::/64
          #gateway: 2001:3984:3989::1
#####################################################################
# SECRETS
# secrets:
  # mysql_passwd:
    # file: ./certs/mysql_passwd
  # mysql_secret_key:
    # file: ./certs/mysql.key
  # mysql_secret_pub:
    # file: ./certs/mysql-public.key
volumes: 
  mysql-data: null