name: Feature Branch

on:
  push:
    branches-ignore:
      - 'main'
      - 'release*'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: -b ci.gradle package